#!/bin/bash
target_dir=$(pwd)/$1
toc_file=$target_dir/000-TOC.md
current=$(grep -hs ^  $toc_file || echo "")

echo "<!-- autogenerated file -->" > $toc_file
echo "# Doc Index - $PROJECT_NAME" >> $toc_file
echo "<!-- TOC -->" >> $toc_file
while IFS= read -r line
do
  line=$(echo $line |  awk  -F "/"  '{print  "["$2"/"$3"]""(""/"$1"/"$2"/"$3")" }')
  if [[ "$line" == *\/\) ]]
  then
     echo "- $line"  >> $toc_file
  else
     echo "  - $line"  >> $toc_file
  fi

done <<< $(find -L _doc -maxdepth 2 -name "*.md" -type f | sort -r)
echo "<!-- /TOC -->" >> $toc_file

new=$(cat $toc_file || echo "")


if [ "$current" == "$new" ]; then
   exit 0
else
   echo "$toc_file has changed 'git add .' before commit"
   exit 127
fi
